config/routes.rb
SiteManchete::Application.routes.draw do
  match '/radios/mostrar', :to => 'radios#mostrar', :as => :mostrar_radio
  resources :radios

  resources :upload_sec_banners

  resources :upload_main_banners

  match '/programacao/dia/prog/:id', :to => 'programacaos#mostrar', :as => :mostrar_programacao
  match '/programacao/dia/:dia', :to => 'programacaos#programacao', :as => :programacao_user
  
  resources :programacaos

  match '/locutores/:id',  :to => 'comunicadores#mostrar', :as => :mostrar_comunicador
  
  match '/locutores',  :to => 'comunicadores#comunicadores', :as => :locutores

  resources :comunicadores

  resources :contatos

  resources :recado_ouvintes

  resources :users

  root :to => 'static_pages#home'
  
  match '/signup',  :to => 'users#new'

  
  match '/noticias/:id',  :to => 'posts#mostrar', :as => :mostrar_noticias
  match '/noticias',  :to => 'posts#noticias', :as => :noticias
  
  resources :posts

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/programacao.rb
class Programacao < ActiveRecord::Base
  attr_accessible :comunicador_id, :descricao, :dia_id, :hora_inicio, :hora_fim, :nome
  belongs_to :comunicadore, :class_name => Comunicadore, :foreign_key => :comunicador_id
  belongs_to :dia
end

app/controllers/programacaos_controller.rb
class ProgramacaosController < ApplicationController
  http_basic_authenticate_with :name => "radio", :password => "radio", :except => :programacao
  # GET /programacao
  # GET /programacao.json
  def programacao

    @upload_sec_banners = UploadSecBanner.all
    @upload_main_banners = UploadMainBanner.all  

    @contato = Contato.new
    @dias = Dia.find(params[:dia])
    @programacaos = @dias.programacaos.paginate(:page => params[:page], :per_page => 2)
    respond_to do |format|
      format.html
      format.json { render :json => @programacaos }
    end
  end
  

  # GET /programacaos
  # GET /programacaos.json
  def index
    @programacaos = Programacao.all

    respond_to do |format|
      format.html { render :layout => 'admin'}
      format.json { render :json => @programacaos }
    end
  end

  # GET /programacao/1
  # GET /programacao/1.json
  def mostrar
    @upload_sec_banners = UploadSecBanner.all
    @upload_main_banners = UploadMainBanner.all  

    @programacao = Programacao.find(params[:id])
    @contato = Contato.new
    respond_to do |format|
      format.html 
      format.json { render :json => @programacao }
    end
  end


  # GET /programacaos/1
  # GET /programacaos/1.json
  def show
    @programacao = Programacao.find(params[:id])
    
    respond_to do |format|
      format.html { render :layout => 'admin'}# show.html.erb
      format.json { render :json => @programacao }
    end
  end

  # GET /programacaos/new
  # GET /programacaos/new.json
  def new
    @programacao = Programacao.new
    
    respond_to do |format|  
      format.html { render :layout => 'admin'}# new.html.erb
      format.json { render :json => @programacao }
    end
  end

  # GET /programacaos/1/edit
  def edit
    @programacao = Programacao.find(params[:id])
    render :layout => 'admin'
  end

  # POST /programacaos
  # POST /programacaos.json
  def create
    @programacao = Programacao.new(params[:programacao])

    respond_to do |format|
      if @programacao.save
        format.html { redirect_to @programacao, :notice => 'Programacao was successfully created.' }
        format.json { render :json => @programacao, :status => :created, :location => @programacao }
      else
        format.html { render :action => "new" }
        format.json { render :json => @programacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /programacaos/1
  # PUT /programacaos/1.json
  def update
    @programacao = Programacao.find(params[:id])

    respond_to do |format|
      if @programacao.update_attributes(params[:programacao])
        format.html { redirect_to @programacao, :notice => 'Programacao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @programacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /programacaos/1
  # DELETE /programacaos/1.json
  def destroy
    @programacao = Programacao.find(params[:id])
    @programacao.destroy

    respond_to do |format|
      format.html { redirect_to programacaos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/programacaos_helper.rb
module ProgramacaosHelper
end

app/views/programacaos/_form.html.erb
<%= form_for(@programacao) do |f| %>
  <% if @programacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@programacao.errors.count, "error") %> prohibited this programacao from being saved:</h2>

      <ul>
      <% @programacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome, :class => "input-large" %>
  </div>
  <div class="field">        
    <%= f.select(:comunicador_id, Comunicadore.all.collect {|p| [ p.nome, p.id ] }, {:prompt => 'Selecione um comunicador'}, :class => "input-large") %>
  </div>
  <div class="field">
    <%= f.select(:dia_id, Dia.all.collect {|p| [ p.nome, p.id ] }, {:prompt => 'Selecione um dia'}, :class => "input-large") %>
  </div>
  <div class="field">
    <%= f.label :hora_inicio %><br />
    <%= f.time_select :hora_inicio, :combined => true,
      :default => Time.now, :class => "input-large" %>
  </div>
 <div class="field">
    <%= f.label :hora_fim %><br />
    <%= f.text_field :hora_fim, :class => "input-large" %>
  </div>  
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao, :rows => "8", :class => "input-xlarge"%>
  </div>
  <div class="actions">
    <%= f.submit "Criar Programação" %>
  </div>
<% end %>

app/views/programacaos/edit.html.erb
<h1>Editar Programação</h1>

<%= render 'form' %>
<div>
<%= link_to 'Mostrar', @programacao, :class => "btn btn-large btn-primary" %>  
<%= link_to 'Voltar', programacaos_path, :class => "btn btn-large btn-primary" %>
</div>

app/views/programacaos/index.html.erb
<h1>Listam de programações</h1>

<% @programacaos.each do |programacao| %>

    <div> Nome: <%= programacao.nome %></div>
     <% if programacao.comunicadore != nil %>
    <div> Comunicador: <%= programacao.comunicadore.nome%></div>
    <%end%>
    <div> Dia: <%= programacao.dia.nome %></div>
    <div> Hora início: <%= programacao.hora_inicio %></div>
    <div> Hora fim <%= programacao.hora_fim %></div>
    <div> Descroção da programação <%= programacao.descricao %></div>
    <br />
    <h3> <%= link_to 'Mostrar', programacao, :class => "btn btn-large btn-primary" %> <%= link_to 'Editar', edit_programacao_path(programacao), :class => "btn btn-large btn-primary" %> <%= link_to 'Excluir', programacao, :class => "btn btn-large btn-primary", :method => :delete, :data => { :confirm => 'Você tem certeza?' } %> </h3>     
    <hr />   
<% end %>


<br />
<br />

<h2><%= link_to 'Nova Programação', new_programacao_path, :class => "btn btn-large btn-primary" %></h2>

app/views/programacaos/mostrar.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @programacao.nome %>
</p>

<p>
  <b>Comunicador:</b>
  <%= @programacao.comunicadore.nome if @programacao.comunicadore %>
</p>

<p>
  <b>Dia:</b>
  <%= Dia.find(@programacao.dia_id).nome %>
</p>

<p>
  <b>Hora Inicio:</b>
  <%= @programacao.hora_inicio %>
</p>

<p>
  <b>Hora Fim:</b>
  <%= @programacao.hora_fim %>
</p>

<p>
  <b>Descricao:</b>
  <%= @programacao.descricao %>
</p>

<%= link_to 'Voltar', programacao_user_path, :class => "btn btn-large btn-primary" %> 

app/views/programacaos/new.html.erb
<h1>Nova Programação</h1>

<%= render 'form' %>
<div>
<%= link_to 'Voltar', programacaos_path, :class => "btn btn-large btn-primary" %>
</div>

app/views/programacaos/programacao.html.erb
<%= render 'layouts/main_banner' %>

<div id="caixa-conteudo">
<h2 id="h2custom">Programação</h2>
<hr>

<nav id="dia-programacao">
  <ul>
  <li><%= link_to "Segunda", "/programacao/dia/1"%></li>
  <li><%= link_to "Terça", "/programacao/dia/2"%></li> 
  <li><%= link_to "Quarta", "/programacao/dia/3"%></li> 
  <li><%= link_to "Quinta", "/programacao/dia/4"%></li> 
  <li><%= link_to "Sexta", "/programacao/dia/5"%></li> 
  <li><%= link_to "Sábado", "/programacao/dia/6"%></li> 
  <li><%= link_to "Domingo", "/programacao/dia/7"%></li> 
  </ul>
</nav>

<% @programacaos.each do |programacao| %>

    <div> Nome: <%= programacao.nome %></div>
    <div> Comunicador: <%= programacao.comunicadore.nome if programacao.comunicadore  %></div>
    <div> Horário: <%= programacao.hora_inicio %></div>
    <div> Descrição da programação <%= programacao.descricao %></div>
    <br/>
    <hr/>   
<% end %>

  <div id="paginacao-noticias">
    <div class="digg_pagination">
      <%= will_paginate @programacaos, :container => false %>
      </div>
  </div>

</div>

<%= render 'layouts/sec_banner' %>

app/views/programacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @programacao.nome %>
</p>

<p>
  <b>Comunicador:</b>
  <%= Comunicadore.find(@programacao.comunicador_id).nome %>
</p>

<p>
  <b>Dia:</b>
  <%= Dia.find(@programacao.dia_id).nome %>
</p>

<p>
  <b>Hora Inicio:</b>
  <%= @programacao.hora_inicio %>
</p>

<p>
  <b>Hora Fim:</b>
  <%= @programacao.hora_fim %>
</p>

<p>
  <b>Descricao:</b>
  <%= @programacao.descricao %>
</p>

<div>
<%= link_to 'Editar', edit_programacao_path(@programacao), :class => "btn btn-large btn-primary" %> 
<%= link_to 'Voltar', programacaos_path, :class => "btn btn-large btn-primary" %> 
</div>