config/routes.rb
SiteManchete::Application.routes.draw do
  match '/radios/mostrar', :to => 'radios#mostrar', :as => :mostrar_radio
  resources :radios

  resources :upload_sec_banners

  resources :upload_main_banners

  match '/programacao/dia/prog/:id', :to => 'programacaos#mostrar', :as => :mostrar_programacao
  match '/programacao/dia/:dia', :to => 'programacaos#programacao', :as => :programacao_user
  
  resources :programacaos

  match '/locutores/:id',  :to => 'comunicadores#mostrar', :as => :mostrar_comunicador
  
  match '/locutores',  :to => 'comunicadores#comunicadores', :as => :locutores

  resources :comunicadores

  resources :contatos

  resources :recado_ouvintes

  resources :users

  root :to => 'static_pages#home'
  
  match '/signup',  :to => 'users#new'

  
  match '/noticias/:id',  :to => 'posts#mostrar', :as => :mostrar_noticias
  match '/noticias',  :to => 'posts#noticias', :as => :noticias
  
  resources :posts

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/comunicadore.rb
class Comunicadore < ActiveRecord::Base
  attr_accessible :contato, :nome, :sobre, :foto
  mount_uploader :foto, NoticiaUploader
end

app/controllers/comunicadores_controller.rb
class ComunicadoresController < ApplicationController
  # GET /comunicadores
  # GET /comunicadores.json
  def index
    @comunicadores = Comunicadore.all
    respond_to do |format|
      format.html { render :layout => 'admin'}# index.html.erb
      format.json { render :json => @comunicadores }
    end
  end

  def comunicadores

    @upload_sec_banners = UploadSecBanner.all
    @upload_main_banners = UploadMainBanner.all  

    @comunicadores = Comunicadore.paginate(:page => params[:page], :per_page => 2)
    @contato = Contato.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @comunicadores }
    end
  end

  # GET /comunicadores/1
  # GET /comunicadores/1.json
  def mostrar
    @upload_sec_banners = UploadSecBanner.all
    @upload_main_banners = UploadMainBanner.all  

    @comunicadore = Comunicadore.find(params[:id])
    @contato = Contato.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @comunicadore }
    end
  end


  # GET /comunicadores/1
  # GET /comunicadores/1.json
  def show
    @comunicadore = Comunicadore.find(params[:id])
    
    respond_to do |format|
      format.html { render :layout => 'admin'}# show.html.erb
      format.json { render :json => @comunicadore }
    end
  end

  # GET /comunicadores/new
  # GET /comunicadores/new.json
  def new
    @comunicadore = Comunicadore.new
    
    respond_to do |format|
      format.html { render :layout => 'admin'}# new.html.erb
      format.json { render :json => @comunicadore }
    end
  end

  # GET /comunicadores/1/edit
  def edit
    @comunicadore = Comunicadore.find(params[:id])    
     render :layout => 'admin'
  end

  # POST /comunicadores
  # POST /comunicadores.json
  def create
    @comunicadore = Comunicadore.new(params[:comunicadore])

    respond_to do |format|
      if @comunicadore.save
        format.html { redirect_to @comunicadore, :notice => 'Comunicadore was successfully created.' }
        format.json { render :json => @comunicadore, :status => :created, :location => @comunicadore }
      else
        format.html { render :action => "new" }
        format.json { render :json => @comunicadore.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comunicadores/1
  # PUT /comunicadores/1.json
  def update
    @comunicadore = Comunicadore.find(params[:id])

    respond_to do |format|
      if @comunicadore.update_attributes(params[:comunicadore])
        format.html { redirect_to @comunicadore, :notice => 'Comunicadore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @comunicadore.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comunicadores/1
  # DELETE /comunicadores/1.json
  def destroy
    @comunicadore = Comunicadore.find(params[:id])
    @comunicadore.destroy

    respond_to do |format|
      format.html { redirect_to comunicadores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comunicadores_helper.rb
module ComunicadoresHelper
end

app/views/comunicadores/_form.html.erb
<%= form_for(@comunicadore) do |f| %>
  <% if @comunicadore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comunicadore.errors.count, "error") %> prohibited this comunicadore from being saved:</h2>

      <ul>
      <% @comunicadore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome, :class => "input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label :sobre %><br />
    <%= f.text_area :sobre, :class => "input-xxlarge", :rows =>"8" %>
  </div>
  <div class="field">
    <%= f.label :contato %><br />
    <%= f.text_field :contato, :class => "input-xxlarge" %>
  </div>

  <div class="field">
    <%= f.label :foto %><br />
    <%= f.file_field :foto, :class => "input-large" %>
  </div>
 
  <div class="actions">
    <%= f.submit "Atualizar comunicadores" %>
  </div>
<% end %>

app/views/comunicadores/comunicadores.html.erb
<%= render 'layouts/main_banner' %>
<div id="caixa-conteudo">
<h2 id="h2custom">Comunicadores</h2>
<hr>

<% @comunicadores.each do |comunicadore| %>
    <div> <%= comunicadore.nome %></div>
	<div> Contato: <%= comunicadore.contato %></div> 
	<div>
	    <div style="position: relative; float: left;"><%= image_tag comunicadore.foto_url.to_s if comunicadore.foto?%> </div>    
	    <div style="position: relative; float: left;"> <%= comunicadore.sobre %></div>           
	</div>
<% end %>

  <div id="paginacao-noticias">
    <div class="digg_pagination">
      <%= will_paginate @comunicadores, :container => false %>
      </div>
  </div>

</div>

<%= render 'layouts/sec_banner' %>

app/views/comunicadores/edit.html.erb
<h1>Editing comunicadore</h1>

<%= render 'form' %>
<div>
<%= link_to 'Mostar', @comunicadore, :class => "btn btn-large btn-primary" %> |
<%= link_to 'Voltar', comunicadores_path, :class => "btn btn-large btn-primary" %>
</div>

app/views/comunicadores/index.html.erb
<h1>Comunicadores</h1>

<table  class="table table-hover">
  <tr>
    <th></th>
    <th>Nome</th>
    <th>Sobre</th>
    <th>Contato</th>
    <th></th>
    <th></th>
    <th></th>    
  </tr>

<% @comunicadores.each do |comunicadore| %>
  <tr>
    <td><%= image_tag comunicadore.foto_url.to_s if comunicadore.foto?%> </td>
    <td><%= comunicadore.nome %></td>
    <td><%= comunicadore.sobre %></td>
    <td><%= comunicadore.contato %></td>    
    <td><%= link_to 'Mostar', comunicadore, :class => "btn btn-large btn-primary" %></td>
    <td><%= link_to 'Editar', edit_comunicadore_path(comunicadore), :class => "btn btn-large btn-primary" %></td>
    <td><%= link_to 'Excluir', comunicadore, :method => :delete, :data => { :confirm => 'Você tem certeza ?' }, :class => "btn btn-large btn-primary" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comunicadore', new_comunicadore_path %>

app/views/comunicadores/mostrar.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @comunicadore.nome %>
</p>

<p>
  <b>Sobre:</b>
  <%= @comunicadore.sobre %>
</p>

<p>
  <b>Contato:</b>
  <%= @comunicadore.contato %>
</p>

<%= link_to 'Voltar', locutores_path %>

app/views/comunicadores/new.html.erb
<h1>Novo comunicador</h1>

<%= render 'form' %>
<div>
<%= link_to 'Voltar', comunicadores_path, :class => "btn btn-large btn-primary" %>
</div>

app/views/comunicadores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @comunicadore.nome %>
</p>

<p>
  <b>Sobre:</b>
  <%= @comunicadore.sobre %>
</p>

<p>
  <b>Contato:</b>
  <%= @comunicadore.contato %>
</p>

<div>
<%= link_to 'Editar', edit_comunicadore_path(@comunicadore), :class => "btn btn-large btn-primary" %> |
<%= link_to 'Voltar', comunicadores_path, :class => "btn btn-large btn-primary" %>
</div>