config/routes.rb
SiteManchete::Application.routes.draw do
  match '/radios/mostrar', :to => 'radios#mostrar', :as => :mostrar_radio
  resources :radios

  resources :upload_sec_banners

  resources :upload_main_banners

  match '/programacao/dia/prog/:id', :to => 'programacaos#mostrar', :as => :mostrar_programacao
  match '/programacao/dia/:dia', :to => 'programacaos#programacao', :as => :programacao_user
  
  resources :programacaos

  match '/locutores/:id',  :to => 'comunicadores#mostrar', :as => :mostrar_comunicador
  
  match '/locutores',  :to => 'comunicadores#comunicadores', :as => :locutores

  resources :comunicadores

  resources :contatos

  resources :recado_ouvintes

  resources :users

  root :to => 'static_pages#home'
  
  match '/signup',  :to => 'users#new'

  
  match '/noticias/:id',  :to => 'posts#mostrar', :as => :mostrar_noticias
  match '/noticias',  :to => 'posts#noticias', :as => :noticias
  
  resources :posts

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'carrierwave/orm/activerecord'

class Post < ActiveRecord::Base
  attr_accessible :description, :title, :manchete, :imagem
  mount_uploader :imagem, NoticiaUploader
  self.per_page = 3
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    
    respond_to do |format|
      format.html { render :layout => 'admin'}# index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    
    respond_to do |format|
      format.html { render :layout => 'admin'}# show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def mostrar
    @upload_sec_banners = UploadSecBanner.all
    @upload_main_banners = UploadMainBanner.all  

    @post = Post.find(params[:id])
    @contato = Contato.new
    respond_to do |format|
      format.html 
      format.json { render :json => @post }
    end
  end

  def noticias
    @upload_sec_banners = UploadSecBanner.all
    @upload_main_banners = UploadMainBanner.all  

    @posts = Post.paginate(:page => params[:page], :per_page => 3)
    @contato = Contato.new
    #@posts.paginate(:page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    
    respond_to do |format|
      format.html{ render :layout => 'admin'} # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])    
    @contato = Contato.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:multipart => true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :manchete %><br />
    <%= f.text_field :manchete %>
  </div>

  <div class="field">
    <%= f.file_field :imagem %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<script type="text/javascript">
$(document).ready(function() {
   if ($('textarea').length > 0) {       
     var data = $('textarea');
     $.each(data, function(i) {
       CKEDITOR.replace(data[i].id);
     });     
   }  
});
</script>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td> 
    
    <td><%= link_to 'Mostrar', post %></td>
    <td><%= link_to 'Editar', edit_post_path(post) %></td>
    <td><%= link_to 'Excluir', post, :method => :delete, :data => { :confirm => 'Você tem certeza ?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/mostrar.html.erb
<%= render 'layouts/main_banner' %>

<div id="caixa-conteudo">
<h2 id="h2custom">Noticías</h2>
<hr>
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo</b>
  <%= @post.title %>
</p>

<p>
  <b>Manchete</b>
  <%= @post.manchete %>
</p>

<p>
  <%= image_tag @post.imagem_url.to_s %>
</p>


<p>
  <b>Notícia</b>
  <%= @post.description.html_safe %>
</p>

<%= link_to 'Voltar', noticias_path %>
</div>

<%= render 'layouts/sec_banner' %>

app/views/posts/new.html.erb
<h1>Nova notícia</h1>

<%= render 'form' %>

<%= link_to 'Voltar', posts_path %>

<script type="text/javascript">
$(document).ready(function() {
   if ($('textarea').length > 0) {       
     var data = $('textarea');
     $.each(data, function(i) {
       CKEDITOR.replace(data[i].id);
     });     
   }  
});
</script>

app/views/posts/noticias.html.erb
<%= render 'layouts/main_banner' %>

<div id="caixa-conteudo">
	<h2 id="h2custom">Notícias</h2>
<hr>
	<table>
	<% @posts.each do |post| %>
	  <tr>
	    <td><%= image_tag post.imagem_url.to_s if post.imagem?%></td>
	    <td> <%= link_to  post.title , mostrar_noticias_path(post) %></td>    
	  </tr>	  
	<% end %>
	</table>

	<div id="paginacao-noticias">
		<div class="digg_pagination">
	    <%= will_paginate @posts, :container => false %>
	  	</div>
	</div>
</div>

<%= render 'layouts/sec_banner' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo</b>
  <%= @post.title %>
</p>

<p>
  <b>Manchete</b>
  <%= @post.manchete %>
</p>

<p>
  <%= image_tag @post.imagem_url.to_s %>
</p>


<p>
  <b>Notícia</b>
  <%= @post.description.html_safe %>
</p>


<%= link_to 'Editar', edit_post_path(@post) %> |
<%= link_to 'Voltar', posts_path %>