config/routes.rb
SiteManchete::Application.routes.draw do
  match '/radios/mostrar', :to => 'radios#mostrar', :as => :mostrar_radio
  resources :radios

  resources :upload_sec_banners

  resources :upload_main_banners

  match '/programacao/dia/prog/:id', :to => 'programacaos#mostrar', :as => :mostrar_programacao
  match '/programacao/dia/:dia', :to => 'programacaos#programacao', :as => :programacao_user
  
  resources :programacaos

  match '/locutores/:id',  :to => 'comunicadores#mostrar', :as => :mostrar_comunicador
  
  match '/locutores',  :to => 'comunicadores#comunicadores', :as => :locutores

  resources :comunicadores

  resources :contatos

  resources :recado_ouvintes

  resources :users

  root :to => 'static_pages#home'
  
  match '/signup',  :to => 'users#new'

  
  match '/noticias/:id',  :to => 'posts#mostrar', :as => :mostrar_noticias
  match '/noticias',  :to => 'posts#noticias', :as => :noticias
  
  resources :posts

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/comunicadore.rb
class Comunicadore < ActiveRecord::Base
  attr_accessible :contato, :nome, :sobre, :foto
  mount_uploader :foto, NoticiaUploader
end

app/models/contato.rb
class Contato < ActiveRecord::Base
  attr_accessible :assunto, :conteudo, :email, :nome
end

app/models/dia.rb
class Dia < ActiveRecord::Base
  attr_accessible :nome
  has_many :programacaos
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'carrierwave/orm/activerecord'

class Post < ActiveRecord::Base
  attr_accessible :description, :title, :manchete, :imagem
  mount_uploader :imagem, NoticiaUploader
  self.per_page = 3
end

app/models/programacao.rb
class Programacao < ActiveRecord::Base
  attr_accessible :comunicador_id, :descricao, :dia_id, :hora_inicio, :hora_fim, :nome
  belongs_to :comunicadore, :class_name => Comunicadore, :foreign_key => :comunicador_id
  belongs_to :dia
end

app/models/radio.rb
class Radio < ActiveRecord::Base
  attr_accessible :descricao
end

app/models/recado_ouvinte.rb
class RecadoOuvinte < ActiveRecord::Base
  attr_accessible :email, :nome, :recado, :telefone
end

app/models/upload_main_banner.rb
class UploadMainBanner < ActiveRecord::Base
  attr_accessible :mainbanner
  mount_uploader :mainbanner, MainbannerUploader
end

app/models/upload_sec_banner.rb
class UploadSecBanner < ActiveRecord::Base
  attr_accessible :secbanner1, :secbanner2, :secbanner3
  mount_uploader :secbanner1, Secbanner1Uploader
  mount_uploader :secbanner2, Secbanner2Uploader
  mount_uploader :secbanner3, Secbanner3Uploader
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { self.email.downcase! }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  			format: { with: VALID_EMAIL_REGEX },
  			uniqueness: {case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    
    respond_to do |format|
      format.html { render :layout => 'admin'}# index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    
    respond_to do |format|
      format.html { render :layout => 'admin'}# show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def mostrar
    @upload_sec_banners = UploadSecBanner.all
    @upload_main_banners = UploadMainBanner.all  

    @post = Post.find(params[:id])
    @contato = Contato.new
    respond_to do |format|
      format.html 
      format.json { render :json => @post }
    end
  end

  def noticias
    @upload_sec_banners = UploadSecBanner.all
    @upload_main_banners = UploadMainBanner.all  

    @posts = Post.paginate(:page => params[:page], :per_page => 3)
    @contato = Contato.new
    #@posts.paginate(:page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    
    respond_to do |format|
      format.html{ render :layout => 'admin'} # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])    
    @contato = Contato.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Radio Manchete"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/comunicadores_helper.rb
module ComunicadoresHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/programacaos_helper.rb
module ProgramacaosHelper
end

app/helpers/radios_helper.rb
module RadiosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, :alt => user.name, :class => "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div id="link-social-networks">
    <div id="facebook">
      <div class="fb-like-box" data-href="http://www.facebook.com/platform" data-width="292" data-height="230" data-colorscheme="dark" data-show-faces="true" data-border-color="blac" data-stream="false" data-header="false"></div>
    </div>

    <div id="twitter">
      <a href="https://twitter.com/manchetelondrina" class="twitter-follow-button" data-show-count="false" data-lang="pt" data-size="large">Seguir @manchetelondrina</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
  </div>
  <div id="contato">
    <h2>Entre em contato conosco</h2>
      <%= form_for(@contato) do |f|%>        
        <div id="contato-info">
          <%= f.text_field :nome, :placeholder => "Nome"%>
          <br/>
          <%= f.text_field :email, :placeholder => "Email"%>
          <br/>
          <%= f.text_field :assunto, :placeholder => "Assunto"%>
        </div>
        <div id="contato-mensagem">
          <%= f.text_field :conteudo, :placeholder => "Menssagem"%>
        </div>        
        <div id="contato-enviar">
          <%= f.submit "Enviar", :class => "btn btn-large btn-primary"%>
        </div>
      <%end%>
  </div>
  <div id="sec-nav">
    <small id="direitos-radio">
      radiomanchetelondrina.com.br | Todos Diretos Reservados
    </small>  
    <nav id="nav-rodape">
      <ul>
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Radio",    mostrar_radio_path %></li>
        <li><%= link_to "Programação", '#' %></li>
        <li><%= link_to "Comunicadores", '#' %></li>
        <li><%= link_to "Recado do ouvinte", '#' %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_footer_admin.html.erb
<footer class="footer-admin">
  <small id="direitos-radio">
    radiomanchetelondrina.com.br | Todos Diretos Reservados
  </small>  
  <nav id="nav-rodape">
    <ul>
      <li><%= link_to "Home",    root_path %></li>
      <li><%= link_to "Radio",    radios_path %></li>
      <li><%= link_to "Programação", '#' %></li>
      <li><%= link_to "Comunicadores", '#' %></li>
      <li><%= link_to "Recado do ouvinte", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<iframe id="radio-on" src="http://playaac.com/64.250.122.179/8032/player.html"></iframe>  
  <div class="navbar-inner">
    <div class="container">
      <%= image_tag  "manchete.png", :size => "230x100", :alt => "Edit Entry", :id => "logo" %>
      <nav id="nav-header">
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path,:class => "btn btn-large btn-primary"  %></li>
          <li><%= link_to "Radio",    mostrar_radio_path %></li>
          <li><%= link_to "Programação", "/programacao/dia/1"%></li>
          <li><%= link_to "Comunicadores", locutores_path %></li>
          <li><%= link_to "Notícias", noticias_path %></li>
          <li><%= link_to "Recado do ouvinte", new_recado_ouvinte_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_header_admin.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">      
      <nav id="nav-header">
        <ul class="nav nav-tabs">
          <li><%= link_to "Pagina inicial",    root_path %></li>
          <li><%= link_to "Gerenciar pagina Radio",    radios_path %></li>
          <li><%= link_to "Gerenciar Programação", programacaos_path %></li>
          <li><%= link_to "Gerenciar Comunicadores", comunicadores_path %></li>
          <li><%= link_to "Gerenciar Notícias", posts_path %></li>
          <li><%= link_to "Gerenciar Recado do ouvinte", recado_ouvintes_path %></li>
          <li><%= link_to "Gerenciar Contatos", contatos_path %></li>
          <li><%= link_to "Gerenciar Banner Principal", upload_main_banners_path %></li>
          <li><%= link_to "Gerenciar Banners Secundários", upload_sec_banners_path %></li>          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_main_banner.html.erb
<div id="main-banner">
    <div id="wrapper">
        <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider" >
                <% @upload_main_banners.each do |upload_main_banner| %>
                    <%= image_tag upload_main_banner.mainbanner_url.to_s if upload_main_banner.mainbanner?%> 
                <% end %>   
            </div>            
        </div>

    </div>
</div>

app/views/layouts/_sec_banner.html.erb
<div id="sec-banner-box">

<div class="sec-banner">
        <div class="slider-wrapper sec-banner-themet">
            <div id="sec-slider1" class="nivoSlider" >
                <% @upload_sec_banners.each do |upload_sec_banner| %>
                    <%= image_tag upload_sec_banner.secbanner1_url.to_s if upload_sec_banner.secbanner1?%>
                <%end%>
            </div>            
        </div>
</div>
<div class="sec-banner">
        <div class="slider-wrapper sec-banner-themet">
            <div id="sec-slider2" class="nivoSlider" >
                <% @upload_sec_banners.each do |upload_sec_banner| %>
                    <%= image_tag upload_sec_banner.secbanner2_url.to_s if upload_sec_banner.secbanner2?%>
                <%end%>
            </div>            
        </div>
</div>
<div class="sec-banner">
        <div class="slider-wrapper sec-banner-themet">
            <div id="sec-slider3" class="nivoSlider" >
                <% @upload_sec_banners.each do |upload_sec_banner| %>
                    <%= image_tag upload_sec_banner.secbanner3_url.to_s if upload_sec_banner.secbanner3?%>
                <%end%>
            </div>            
        </div>
</div>
</div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application_admin", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "jquery.tools.min" %>
    <%= javascript_include_tag "jquery.nivo.slider" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="fb-root"></div>
    <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>

 	<%= render 'layouts/header_admin' %>
    <div class="container" id="conteudo">
      <%= yield %>
      <%= render 'layouts/footer_admin' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "jquery.tools.min" %>
    <%= javascript_include_tag "jquery.nivo.slider" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="fb-root"></div>
    <script>
       (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
    <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>

 	<%= render 'layouts/header' %>
    <div class="container" id="conteudo">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
   <script type="text/javascript">   
    $(window).load(function() {          
        $('#slider').nivoSlider({controlNav: false});
        $('#sec-slider1').nivoSlider({directionNav: false, controlNav: false});
        $('#sec-slider2').nivoSlider({directionNav: false, controlNav: false});
        $('#sec-slider3').nivoSlider({directionNav: false, controlNav: false});        
    });
   </script>
  </body>
</html>